version: '3.4'

services:
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    volumes:
      - .:/home/dynamodblocal/data
    ports: 
      - 8000:8000
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/'

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on:
      - dynamodb
  
  dynamodb_migrator:
    image: amazon/aws-cli
    container_name: app-dynamodb_migrator
    working_dir: /home/dynamodblocal
    command: dynamodb create-table --cli-input-json file://slack-table.json --endpoint-url http://dynamodb:8000
    volumes:
      - ./schema:/home/dynamodblocal
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on:
      - dynamodb

  base:
    image: contentful/slack-app-base
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - '.:/usr/src/app'
    ports:
      - 3000:3000
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DYNAMO_TABLE_NAME: sls-apps-slack-backend-dev-TokenTable
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
